// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCucbNohY6Q_93d9Xz0WZoYsExVtui_2tY',
    appId: '1:540533673971:web:798902b56f7e6ebab24c86',
    messagingSenderId: '540533673971',
    projectId: 'blood-donation-c45b9',
    authDomain: 'blood-donation-c45b9.firebaseapp.com',
    databaseURL: 'https://blood-donation-c45b9-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-c45b9.appspot.com',
    measurementId: 'G-KG2TR9WS61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5PN8AjcCfDBPCLwZuG7DigszedPm4NSA',
    appId: '1:540533673971:android:98fe9322005991f5b24c86',
    messagingSenderId: '540533673971',
    projectId: 'blood-donation-c45b9',
    databaseURL: 'https://blood-donation-c45b9-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-c45b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7z4jiKxNtVtiiCYu0iPH59TcoXgt-7oI',
    appId: '1:540533673971:ios:e9354c8541117444b24c86',
    messagingSenderId: '540533673971',
    projectId: 'blood-donation-c45b9',
    databaseURL: 'https://blood-donation-c45b9-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-c45b9.appspot.com',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7z4jiKxNtVtiiCYu0iPH59TcoXgt-7oI',
    appId: '1:540533673971:ios:a676030a0443d526b24c86',
    messagingSenderId: '540533673971',
    projectId: 'blood-donation-c45b9',
    databaseURL: 'https://blood-donation-c45b9-default-rtdb.firebaseio.com',
    storageBucket: 'blood-donation-c45b9.appspot.com',
    iosBundleId: 'com.example.firebase.RunnerTests',
  );
}
